const LOAD_FAVORITE_ACTIVITIES = "LOAD_FAVORITE_ACTIVITIES";
const ADD_FAVORITE_ACTIVITY = "ADD_FAVORITE_ACTIVITY";
const REMOVE_FAVORITE_ACTIVITY = "REMOVE_FAVORITE_ACTIVITY";
const LOAD_PLANS = "LOAD_PLANS";
const ADD_PLAN = "ADD_PLAN";
const ADD_ACTIVITY_TO_PLAN = "ADD_ACTIVITY_TO_PLAN";
const REMOVE_ACTIVITY_FROM_PLAN = "REMOVE_ACTIVITY_FROM_PLAN";
const SET_TOKEN = "SET_TOKEN";
const REMOVE_TOKEN = "REMOVE_TOKEN";
const RESET_ALL = "RESET_ALL";
const SHOW_ERR = "SHOW_ERR";

export {
  LOAD_FAVORITE_ACTIVITIES,
  ADD_FAVORITE_ACTIVITY,
  REMOVE_FAVORITE_ACTIVITY,
  LOAD_PLANS,
  ADD_PLAN,
  ADD_ACTIVITY_TO_PLAN,
  REMOVE_ACTIVITY_FROM_PLAN,
  SET_TOKEN,
  REMOVE_TOKEN,
  RESET_ALL,
  SHOW_ERR
};